// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef StoryzInterface_h
#define StoryzInterface_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Menu_Bar.H>
extern void menuNew(Fl_Menu_*, void*);
extern void menuOpen(Fl_Menu_*, void*);
extern void menuSave(Fl_Menu_*, void*);
extern void menuSaveAs(Fl_Menu_*, void*);
extern void menuQuit(Fl_Menu_*, void*);
extern void menuOpenCharacter(Fl_Menu_*, void*);
extern void menuOpenPlan(Fl_Menu_*, void*);
extern void menuOpenMap(Fl_Menu_*, void*);
extern void menuOpenNote(Fl_Menu_*, void*);
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
extern void toolbarOpenCharacter(Fl_Button*, void*);
extern void toolbarOpenNote(Fl_Button*, void*);
extern void characterListNew(Fl_Button*, void*);
extern void characterListDelete(Fl_Button*, void*);
extern void characterListUp(Fl_Button*, void*);
extern void characterListDown(Fl_Button*, void*);
#include <FL/Fl_Browser.H>
extern void characterListCallback(Fl_Browser*, void*);
#include <FL/Fl_Input.H>
extern void characterNameCallback(Fl_Input*, void*);
#include <FL/Fl_Text_Editor.H>
extern void noteListCallback(Fl_Browser*, void*);
extern void noteListNew(Fl_Button*, void*);
extern void noteListDelete(Fl_Button*, void*);
extern void noteListUp(Fl_Button*, void*);
extern void noteListDown(Fl_Button*, void*);
extern void noteNameCallback(Fl_Input*, void*);
extern void planListCallback(Fl_Browser*, void*);
extern void planListNew(Fl_Button*, void*);
extern void planListDelete(Fl_Button*, void*);
extern void planListUp(Fl_Button*, void*);
extern void planListDown(Fl_Button*, void*);
extern void planNameCallback(Fl_Input*, void*);
extern void planImageLoad(Fl_Button*, void*);
extern void planImageZoomIn(Fl_Button*, void*);
extern void planImageZoomOut(Fl_Button*, void*);
extern void planImageFull(Fl_Button*, void*);
extern void planImageClear(Fl_Button*, void*);
#include <FL/Fl_Scroll.H>
#include <FL/Fl_Box.H>
extern void mapListCallback(Fl_Browser*, void*);
extern void mapListNew(Fl_Button*, void*);
extern void mapListDelete(Fl_Button*, void*);
extern void mapListUp(Fl_Button*, void*);
extern void mapListDown(Fl_Button*, void*);
extern void mapNameCallback(Fl_Input*, void*);

class MainInterface {
public:
  MainInterface();
  Fl_Double_Window *mainWindow;
  Fl_Menu_Bar *mainMenu;
  static Fl_Menu_Item menu_mainMenu[];
  static Fl_Menu_Item *menuFile;
  Fl_Group *mainToolbar;
  Fl_Button *btnPerso;
  Fl_Button *btnBook;
  Fl_Button *btnNote;
  Fl_Group *mainView;
  Fl_Double_Window *characterWindow;
  Fl_Browser *characterList;
  Fl_Input *characterName;
  Fl_Input *characterFullName;
  Fl_Input *characterGender;
  Fl_Input *characterAge;
  Fl_Input *characterSize;
  Fl_Input *characterWeight;
  Fl_Text_Editor *characterDescription;
  Fl_Text_Editor *characterActions;
  Fl_Text_Editor *characterGoals;
  Fl_Text_Editor *characterLinks;
  Fl_Double_Window *noteWindow;
  Fl_Browser *noteList;
  Fl_Text_Editor *noteText;
  Fl_Input *noteName;
  Fl_Double_Window *planWindow;
  Fl_Browser *planList;
  Fl_Text_Editor *planText;
  Fl_Input *planName;
  Fl_Box *planImageBox;
  Fl_Double_Window *mapWindow;
  Fl_Browser *mapList;
  Fl_Text_Editor *mapText;
  Fl_Input *mapName;
};
#endif
